import type { AppNotification, CustomerRequest, Message, Offer, Provider, Vehicle } from './models';
export const initialVehicles: Vehicle[] = [
  {
    id: 'v1',
    maker: 'تويوتا',
    model: 'كامري',
    year: '2019',
    engine: '2.5',
    fuel: 'بنزين',
    notes: 'مركبة تجريبية',
  },
  { id: 'v2', maker: 'كيا', model: 'سورينتو', year: '2021', engine: '2.0', fuel: 'بنزين' },
];
export const providers: Provider[] = [
  {
    id: 'p1',
    name: 'مركز دجلة التجريبي',
    activity: 'صيانة سيارات',
    activities: ['صيانة', 'كهرباء', 'إطارات'],
    area: 'الكرادة - بغداد',
    rating: 4.8,
    reviews: 126,
    distance: '٣٫٢ كم',
    description: 'مركز خدمة تجريبي متعدد الاختصاصات. جميع البيانات للعرض فقط.',
    brands: ['تويوتا', 'كيا', 'فورد'],
    hours: 'يومياً، ٨ ص–٨ م',
  },
  {
    id: 'p2',
    name: 'ورشة الرافدين التجريبية',
    activity: 'ميكانيك وكهرباء',
    activities: ['محركات', 'كهرباء'],
    area: 'المنصور - بغداد',
    rating: 4.5,
    reviews: 72,
    distance: '٥٫١ كم',
    description: 'ورشة وهمية لا تمثل نشاطاً حقيقياً.',
    brands: ['جميع العلامات'],
    hours: 'السبت–الخميس، ٩ ص–٧ م',
  },
  {
    id: 'p3',
    name: 'متجر النخلة التجريبي',
    activity: 'قطع غيار',
    activities: ['قطع غيار', 'بطاريات'],
    area: 'الكرادة - بغداد',
    rating: 4.3,
    reviews: 44,
    distance: '٢٫٤ كم',
    description: 'متجر بياناته خيالية لأغراض اختبار النموذج.',
    brands: ['تويوتا', 'هيونداي'],
    hours: 'يومياً، ٩ ص–٩ م',
  },
];
export const initialRequests: CustomerRequest[] = [
  {
    id: 'REQ-1048',
    service: 'maintenance',
    vehicleId: 'v1',
    description: 'صوت غير معتاد عند تشغيل المحرك.',
    area: 'الكرادة - بغداد',
    details: { العطل: 'المحرك، النظام الكهربائي' },
    images: ['صورة ١'],
    status: 'receiving',
    createdAt: '٢٠٢٦/٠٧/٢٨',
  },
  {
    id: 'REQ-1032',
    service: 'parts',
    vehicleId: 'v2',
    description: 'أحتاج قطعة تبديل أصلية أو بديل جيد.',
    area: 'الكرادة - بغداد',
    details: { القطعة: 'مضخة ماء', الكمية: '١' },
    images: [],
    status: 'accepted',
    acceptedOfferId: 'o4',
    createdAt: '٢٠٢٦/٠٧/٢٠',
  },
  {
    id: 'REQ-1011',
    service: 'tires',
    vehicleId: 'v1',
    description: 'تبديل أربعة إطارات مع التركيب.',
    area: 'المنصور - بغداد',
    details: { القياس: '215/55 R17' },
    images: [],
    status: 'completed',
    createdAt: '٢٠٢٦/٠٧/١٠',
  },
  {
    id: 'REQ-1002',
    service: 'towing',
    vehicleId: 'v2',
    description: 'نقل المركبة إلى الورشة.',
    area: 'الكرادة - بغداد',
    address: 'قرب ساحة عامة - عنوان تجريبي',
    details: { الوجهة: 'المنصور' },
    images: [],
    status: 'cancelled',
    cancellationReason: 'تم تشغيل المركبة ولم أعد أحتاج الكرين.',
    createdAt: '٢٠٢٦/٠٧/٠٢',
  },
];
export const initialOffers: Offer[] = [
  {
    id: 'o1',
    requestId: 'REQ-1048',
    providerId: 'p1',
    status: 'active',
    priceType: 'estimated',
    price: '١٢٠٬٠٠٠ – ١٨٠٬٠٠٠ د.ع',
    appointment: 'غداً، ١٠:٠٠ ص',
    parts: false,
    message: 'نحتاج إلى فحص المركبة لتحديد السبب والسعر النهائي.',
  },
  {
    id: 'o2',
    requestId: 'REQ-1048',
    providerId: 'p2',
    status: 'active',
    priceType: 'fixed',
    price: '١٥٠٬٠٠٠ د.ع',
    appointment: 'اليوم، ٤:٠٠ م',
    parts: true,
    message: 'يشمل العرض الفحص وقطع الاستهلاك البسيطة.',
  },
  {
    id: 'o3',
    requestId: 'REQ-1048',
    providerId: 'p3',
    status: 'active',
    priceType: 'estimated',
    price: '٩٠٬٠٠٠ – ١٤٠٬٠٠٠ د.ع',
    appointment: 'بعد غد',
    parts: false,
    message: 'عرض تجريبي للمقارنة.',
  },
  {
    id: 'o4',
    requestId: 'REQ-1032',
    providerId: 'p3',
    status: 'accepted',
    priceType: 'fixed',
    price: '٨٥٬٠٠٠ د.ع',
    appointment: 'متوفر الآن',
    parts: true,
    message: 'القطعة متوفرة مع ضمان تجريبي.',
  },
];
export const initialMessages: Message[] = [
  {
    id: 'm1',
    requestId: 'REQ-1048',
    providerId: 'p1',
    mine: false,
    text: 'مرحباً، هل يظهر الصوت والمحرك بارد؟',
    time: '١٠:٢٥ ص',
  },
];
export const initialNotifications: AppNotification[] = [
  {
    id: 'n1',
    title: 'وصل عرض جديد',
    body: 'أرسل مركز دجلة عرضاً لطلب الصيانة.',
    time: 'منذ ٥ دقائق',
    read: false,
    target: '/request/REQ-1048',
  },
  {
    id: 'n2',
    title: 'تم قبول العرض',
    body: 'عرض قطع الغيار مقبول ويمكنك التواصل مع المتجر.',
    time: 'أمس',
    read: true,
    target: '/request/REQ-1032',
  },
  {
    id: 'n3',
    title: 'تذكير بالتقييم',
    body: 'قيّم تجربتك للطلب المكتمل.',
    time: 'منذ ٥ أيام',
    read: false,
    target: '/rating/REQ-1011',
  },
  {
    id: 'n4',
    title: 'إعلان إداري تجريبي',
    body: 'جميع الخدمات والبيانات في هذا التطبيق محاكية.',
    time: 'منذ أسبوع',
    read: true,
    target: '/notifications',
  },
];
export const banners = [
  {
    id: 'b1',
    title: 'افحص سيارتك قبل السفر',
    description: 'أنشئ طلب صيانة واستلم عروضاً مناسبة.',
    icon: '🛠️',
    action: '/request/new?service=maintenance',
  },
  {
    id: 'b2',
    title: 'خدمة متنقلة إلى موقعك',
    description: 'اكتب عنوانك وسيصل طلبك لمقدمي الخدمة المطابقين.',
    icon: '🚐',
    action: '/request/new?service=mobile',
  },
  {
    id: 'b3',
    title: 'بيانات محلية وآمنة',
    description: 'هذا نموذج تجريبي ولا يرسل بياناتك إلى خادم.',
    icon: '✓',
    action: '/legal/usage',
  },
];
