import type {
  AdminReportSummary,
  AdvertisingBanner,
  AccountDeletionRequest,
  AppSettings,
  Area,
  Complaint,
  Conversation,
  Customer,
  FaultCategory,
  FAQItem,
  LegalDocument,
  Message,
  Notification,
  NotificationDelivery,
  NotificationPreference,
  Offer,
  Provider,
  ProviderActivity,
  ProviderDocument,
  Report,
  Review,
  ServiceCategory,
  ServiceRequest,
  SupportConversation,
  Vehicle,
} from '@mzad/shared-types';
import { faultLabels, serviceLabels } from '@mzad/shared-types/labels';

const T = '2026-01-10T09:00:00.000Z';
export const mockAreas: Area[] = [
  {
    id: 'area-baghdad-karrada',
    governorate: 'بغداد',
    city: 'بغداد',
    name: 'الكرادة',
    isActive: true,
  },
  {
    id: 'area-baghdad-mansour',
    governorate: 'بغداد',
    city: 'بغداد',
    name: 'المنصور',
    isActive: true,
  },
  { id: 'area-basra-ashar', governorate: 'البصرة', city: 'البصرة', name: 'العشار', isActive: true },
];
export const mockCustomers: Customer[] = [
  {
    id: 'customer-001',
    name: 'سارة التجريبية',
    phone: '+9647900000001',
    areaId: 'area-baghdad-karrada',
    status: 'active',
    phoneVerified: true,
    acceptedTermsAt: T,
    acceptedPrivacyAt: T,
    createdAt: T,
  },
  {
    id: 'customer-002',
    name: 'حيدر التجريبي',
    phone: '+9647900000002',
    areaId: 'area-basra-ashar',
    status: 'active',
    phoneVerified: true,
    acceptedTermsAt: T,
    acceptedPrivacyAt: T,
    createdAt: T,
  },
  {
    id: 'customer-003',
    name: 'نور التجريبية',
    phone: '+9647900000003',
    areaId: 'area-baghdad-mansour',
    status: 'deletion_pending',
    phoneVerified: true,
    acceptedTermsAt: T,
    acceptedPrivacyAt: T,
    createdAt: T,
  },
];
const serviceCodes = [
  'maintenance',
  'spare_parts',
  'mobile_service',
  'towing',
  'tires',
  'batteries',
  'car_glass',
  'accessories',
] as const;
export const mockProviderActivities: ProviderActivity[] = serviceCodes.map((code) => ({
  id: code,
  serviceCode: code,
  nameAr: serviceLabels[code],
  isActive: true,
}));
const hours = [{ day: 0, opensAt: '08:00', closesAt: '18:00', isClosed: false }];
export const mockProviders: Provider[] = [
  {
    id: 'provider-001',
    responsiblePersonName: 'مسؤول الورشة التجريبي',
    businessName: 'مركز الرافدين التجريبي',
    phone: '+9647900000101',
    phoneVerified: true,
    status: 'approved',
    activityIds: ['maintenance', 'mobile_service', 'tires', 'batteries'],
    supportedVehicleBrands: ['Toyota', 'Kia', 'Ford'],
    areaId: 'area-baghdad-karrada',
    fullAddress: 'عنوان تجريبي، الكرادة، بغداد',
    workingHours: hours,
    businessImageUrls: ['mock://provider/001/business.webp'],
    logoUrl: 'mock://provider/001/logo.webp',
    acceptedTermsAt: T,
    acceptedPrivacyAt: T,
    acceptedUsageInstructionsAt: T,
    rating: 4.6,
    ratingCount: 28,
    createdAt: T,
  },
  {
    id: 'provider-002',
    responsiblePersonName: 'مسؤول السحب التجريبي',
    businessName: 'نقل دجلة التجريبي',
    phone: '+9647900000102',
    phoneVerified: true,
    status: 'approved',
    activityIds: ['towing'],
    supportedVehicleBrands: ['جميع العلامات'],
    areaId: 'area-baghdad-karrada',
    fullAddress: 'عنوان تجريبي، بغداد',
    location: { latitude: 33.3, longitude: 44.4 },
    workingHours: hours,
    businessImageUrls: ['mock://provider/002/business.webp'],
    logoUrl: 'mock://provider/002/logo.webp',
    acceptedTermsAt: T,
    acceptedPrivacyAt: T,
    acceptedUsageInstructionsAt: T,
    rating: 4.2,
    ratingCount: 11,
    createdAt: T,
  },
  {
    id: 'provider-003',
    responsiblePersonName: 'مسؤول المتجر التجريبي',
    businessName: 'قطع النخيل التجريبية',
    phone: '+9647900000103',
    phoneVerified: true,
    status: 'pending',
    activityIds: ['spare_parts', 'accessories'],
    supportedVehicleBrands: ['Toyota', 'Hyundai'],
    areaId: 'area-basra-ashar',
    fullAddress: 'عنوان تجريبي، العشار، البصرة',
    workingHours: hours,
    businessImageUrls: ['mock://provider/003/business.webp'],
    logoUrl: 'mock://provider/003/logo.webp',
    acceptedTermsAt: T,
    acceptedPrivacyAt: T,
    acceptedUsageInstructionsAt: T,
    rating: 0,
    ratingCount: 0,
    createdAt: T,
  },
  {
    id: 'provider-004',
    responsiblePersonName: 'مسؤول معلق تجريبي',
    businessName: 'بطارية الفرات التجريبية',
    phone: '+9647900000104',
    phoneVerified: true,
    status: 'temporarily_suspended',
    activityIds: ['batteries', 'mobile_service'],
    supportedVehicleBrands: ['جميع العلامات'],
    areaId: 'area-baghdad-mansour',
    fullAddress: 'عنوان تجريبي، المنصور، بغداد',
    workingHours: hours,
    businessImageUrls: ['mock://provider/004/business.webp'],
    logoUrl: 'mock://provider/004/logo.webp',
    acceptedTermsAt: T,
    acceptedPrivacyAt: T,
    acceptedUsageInstructionsAt: T,
    rating: 3.8,
    ratingCount: 5,
    createdAt: T,
  },
];
export const mockProviderDocuments: ProviderDocument[] = [
  {
    id: 'document-001',
    providerId: 'provider-001',
    type: 'identity',
    mockFileUrl: 'mock://documents/fictional-identity.pdf',
    status: 'approved',
    reviewedAt: T,
  },
  {
    id: 'document-002',
    providerId: 'provider-003',
    type: 'practice_license',
    mockFileUrl: 'mock://documents/fictional-license.pdf',
    status: 'pending',
  },
];
export const mockVehicles: Vehicle[] = [
  {
    id: 'vehicle-001',
    customerId: 'customer-001',
    manufacturer: 'Toyota',
    model: 'Camry',
    manufacturingYear: 2019,
    engineSize: '2.5',
    fuelType: 'petrol',
    additionalDetails: 'بيانات تجريبية فقط',
    createdAt: T,
  },
  {
    id: 'vehicle-002',
    customerId: 'customer-001',
    manufacturer: 'Kia',
    model: 'Sorento',
    manufacturingYear: 2021,
    engineSize: '2.0',
    fuelType: 'petrol',
    vin: 'MOCKVIN00000000001',
    createdAt: T,
  },
  {
    id: 'vehicle-003',
    customerId: 'customer-002',
    manufacturer: 'Ford',
    model: 'Focus',
    manufacturingYear: 2018,
    engineSize: '2.0',
    fuelType: 'petrol',
    createdAt: T,
  },
];
const expiry: Record<(typeof serviceCodes)[number], number> = {
  maintenance: 168,
  spare_parts: 168,
  mobile_service: 72,
  towing: 6,
  tires: 168,
  batteries: 168,
  car_glass: 168,
  accessories: 168,
};
export const mockServiceCategories: ServiceCategory[] = serviceCodes.map((code, index) => ({
  id: code,
  code,
  nameAr: serviceLabels[code],
  displayOrder: index + 1,
  isActive: true,
  requiresDetailedAddress: code === 'towing' || code === 'mobile_service',
  expiryHours: expiry[code],
}));
const faultCodes = [
  'unknown',
  'engine',
  'electrical',
  'cooling_ac',
  'brakes',
  'suspension_steering',
  'transmission',
  'inspection_diagnostics',
  'periodic_maintenance',
  'painting_body',
  'wrapping_upholstery',
  'exhaust_performance',
  'other',
] as const;
export const mockFaultCategories: FaultCategory[] = faultCodes.map((code, index) => ({
  id: code,
  code,
  nameAr: faultLabels[code],
  displayOrder: index + 1,
  isActive: true,
}));
export const mockRequests: ServiceRequest[] = [
  {
    id: 'request-maintenance',
    customerId: 'customer-001',
    vehicleId: 'vehicle-001',
    serviceCategoryId: 'maintenance',
    faultCategoryIds: ['engine', 'electrical'],
    description: 'ضعف تجريبي في تشغيل المحرك مع تنبيه كهربائي.',
    location: { areaId: 'area-baghdad-karrada' },
    attachments: [
      { id: 'attachment-1', type: 'image', mockUrl: 'mock://requests/1.webp' },
      { id: 'attachment-2', type: 'image', mockUrl: 'mock://requests/2.webp' },
      { id: 'attachment-3', type: 'image', mockUrl: 'mock://requests/3.webp' },
    ],
    status: 'receiving_offers',
    submittedAt: '2026-01-11T08:00:00.000Z',
    expiresAt: '2026-01-18T08:00:00.000Z',
  },
  {
    id: 'request-towing',
    customerId: 'customer-001',
    vehicleId: 'vehicle-002',
    serviceCategoryId: 'towing',
    faultCategoryIds: [],
    description: 'طلب سحب تجريبي لمركبة متوقفة.',
    location: {
      areaId: 'area-baghdad-karrada',
      fullAddress: 'عنوان تجريبي قرب ساحة عامة',
      coordinates: { latitude: 33.31, longitude: 44.41 },
    },
    attachments: [],
    status: 'offer_accepted',
    acceptedOfferId: 'offer-towing-accepted',
    submittedAt: '2026-01-12T08:00:00.000Z',
    expiresAt: '2026-01-12T14:00:00.000Z',
  },
  {
    id: 'request-mobile',
    customerId: 'customer-002',
    vehicleId: 'vehicle-003',
    serviceCategoryId: 'mobile_service',
    faultCategoryIds: ['unknown'],
    description: 'المركبة لا تعمل، السبب غير معروف.',
    location: { areaId: 'area-basra-ashar', fullAddress: 'عنوان تجريبي في العشار' },
    attachments: [],
    status: 'submitted',
    submittedAt: '2026-01-13T08:00:00.000Z',
    expiresAt: '2026-01-16T08:00:00.000Z',
  },
  {
    id: 'request-parts-completed',
    customerId: 'customer-001',
    vehicleId: 'vehicle-001',
    serviceCategoryId: 'spare_parts',
    faultCategoryIds: [],
    description: 'طلب تجريبي لقطعة تبديل.',
    location: { areaId: 'area-baghdad-karrada' },
    sparePartOption: 'parts_only',
    attachments: [],
    status: 'completed',
    acceptedOfferId: 'offer-parts-fixed',
    submittedAt: '2025-12-01T08:00:00.000Z',
    expiresAt: '2025-12-08T08:00:00.000Z',
    completedAt: '2025-12-03T11:00:00.000Z',
  },
  {
    id: 'request-cancelled',
    customerId: 'customer-002',
    vehicleId: 'vehicle-003',
    serviceCategoryId: 'tires',
    faultCategoryIds: [],
    description: 'طلب إطارات تجريبي.',
    location: { areaId: 'area-basra-ashar' },
    attachments: [],
    status: 'cancelled',
    cancellation: {
      reason: 'لم تعد الخدمة مطلوبة.',
      cancelledBy: 'customer',
      cancelledAt: '2025-12-05T12:00:00.000Z',
    },
    submittedAt: '2025-12-04T08:00:00.000Z',
    expiresAt: '2025-12-11T08:00:00.000Z',
  },
  {
    id: 'request-expired',
    customerId: 'customer-001',
    vehicleId: 'vehicle-002',
    serviceCategoryId: 'car_glass',
    faultCategoryIds: [],
    description: 'طلب زجاج تجريبي منتهي.',
    location: { areaId: 'area-baghdad-mansour' },
    attachments: [],
    status: 'expired',
    submittedAt: '2025-11-01T08:00:00.000Z',
    expiresAt: '2025-11-08T08:00:00.000Z',
  },
];
export const mockOffers: Offer[] = [
  {
    id: 'offer-maintenance-estimated',
    requestId: 'request-maintenance',
    providerId: 'provider-001',
    status: 'active',
    price: { kind: 'estimated', minimumIqd: 100000, maximumIqd: 160000 },
    availableAppointment: '2026-01-12T09:00:00.000Z',
    estimatedWorkDuration: 'يومان',
    partsIncluded: false,
    warrantyInformation: 'ضمان تجريبي لمدة شهر',
    providerMessage: 'يتحدد السعر بعد الفحص.',
    imageUrls: [],
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'offer-towing-accepted',
    requestId: 'request-towing',
    providerId: 'provider-002',
    status: 'accepted',
    price: { kind: 'fixed', amountIqd: 45000 },
    estimatedWorkDuration: 'ساعة واحدة',
    partsIncluded: false,
    imageUrls: [],
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'offer-towing-other',
    requestId: 'request-towing',
    providerId: 'provider-001',
    status: 'not_accepted',
    price: { kind: 'fixed', amountIqd: 50000 },
    imageUrls: [],
    createdAt: T,
    updatedAt: T,
  },
  {
    id: 'offer-parts-fixed',
    requestId: 'request-parts-completed',
    providerId: 'provider-001',
    status: 'accepted',
    price: { kind: 'fixed', amountIqd: 75000 },
    partsIncluded: true,
    imageUrls: ['mock://offers/part.webp'],
    createdAt: T,
    updatedAt: T,
  },
];
export const mockConversations: Conversation[] = [
  {
    id: 'conversation-001',
    requestId: 'request-towing',
    customerId: 'customer-001',
    providerId: 'provider-002',
    administrationVisible: true,
    createdAt: T,
  },
];
export const mockMessages: Message[] = [
  {
    id: 'message-001',
    conversationId: 'conversation-001',
    senderId: 'customer-001',
    senderType: 'customer',
    recipientId: 'provider-002',
    text: 'مرحباً، هذا نص تجريبي عن موقع المركبة.',
    sentAt: T,
    deliveryStatus: 'delivered',
    readAt: '2026-01-10T09:01:00.000Z',
  },
];
export const mockReviews: Review[] = [
  {
    id: 'review-001',
    requestId: 'request-parts-completed',
    customerId: 'customer-001',
    providerId: 'provider-001',
    rating: 5,
    comment: 'خدمة تجريبية جيدة.',
    reply: {
      id: 'reply-001',
      reviewId: 'review-001',
      providerId: 'provider-001',
      text: 'شكراً لتقييمك.',
      createdAt: T,
      updatedAt: T,
    },
    isHidden: false,
    createdAt: T,
    updatedAt: T,
  },
];
export const mockComplaints: Complaint[] = [
  {
    id: 'complaint-001',
    reason: 'offer_mismatch',
    status: 'under_review',
    description: 'شكوى تجريبية لا تخص أشخاصاً حقيقيين.',
    customerId: 'customer-001',
    providerId: 'provider-002',
    requestId: 'request-towing',
    createdAt: T,
  },
];
export const mockReports: Report[] = [
  {
    id: 'report-001',
    reporterId: 'customer-001',
    reporterType: 'customer',
    reportedUserId: 'provider-002',
    reason: 'provider_conduct',
    description: 'بلاغ تجريبي لا يشير إلى شخص حقيقي.',
    requestId: 'request-towing',
    status: 'submitted',
    createdAt: T,
  },
];
export const mockSupportConversations: SupportConversation[] = [
  {
    id: 'support-001',
    userId: 'customer-001',
    userType: 'customer',
    subject: 'استفسار تجريبي',
    messageIds: [],
    status: 'open',
    createdAt: T,
  },
];
export const mockBanners: AdvertisingBanner[] = [
  {
    id: 'banner-customer-001',
    title: 'نصيحة تجريبية للسيارة',
    description: 'إعلان محاكى لتطبيق الزبائن.',
    buttonLabel: 'اعرف المزيد',
    destination: { type: 'internal', path: '/mock-tip' },
    startsAt: '2026-01-01T00:00:00.000Z',
    endsAt: '2027-01-01T00:00:00.000Z',
    displayOrder: 1,
    isActive: true,
    target: { application: 'customer', userType: 'customer' },
    statistic: { bannerId: 'banner-customer-001', impressionCount: 1250, clickCount: 81 },
  },
  {
    id: 'banner-provider-001',
    title: 'تعليمات مقدمي الخدمة',
    description: 'إعلان محاكى لتطبيق مقدمي الخدمة.',
    destination: { type: 'none' },
    startsAt: '2026-01-01T00:00:00.000Z',
    endsAt: '2027-01-01T00:00:00.000Z',
    displayOrder: 1,
    isActive: true,
    target: { application: 'provider', userType: 'provider' },
    statistic: { bannerId: 'banner-provider-001', impressionCount: 620, clickCount: 20 },
  },
];
export const mockNotifications: Notification[] = [
  {
    id: 'notification-001',
    title: 'تذكير تجريبي',
    message: 'هذه رسالة مجدولة ومحاكية.',
    type: 'administration',
    channels: ['in_app', 'simulated_push'],
    target: { kind: 'all_customers' },
    status: 'scheduled',
    scheduledAt: '2026-02-01T09:00:00.000Z',
    createdAt: T,
  },
];
export const mockNotificationPreferences: NotificationPreference[] = [
  {
    userId: 'customer-001',
    userType: 'customer',
    disabledTypes: ['marketing'],
    simulatedPushEnabled: true,
  },
];
export const mockNotificationDeliveries: NotificationDelivery[] = [
  {
    id: 'delivery-001',
    notificationId: 'notification-001',
    recipientId: 'customer-001',
    recipientType: 'customer',
    status: 'pending',
  },
];
export const mockSettings: AppSettings = {
  id: 'app_settings',
  maximumValidOffers: 7,
  towingExpiryHours: 6,
  mobileServiceExpiryHours: 72,
  defaultRequestExpiryHours: 168,
  completionReminderDays: 5,
  accountDeletionWaitingHours: 48,
  deletedDataRetentionMonths: 6,
  bannerRotationSeconds: 5,
};
export const mockAccountDeletionRequests: AccountDeletionRequest[] = [
  {
    id: 'deletion-001',
    customerId: 'customer-003',
    reason: 'طلب تجريبي',
    requestedAt: '2026-01-10T09:00:00.000Z',
    scheduledDeletionAt: '2026-01-12T09:00:00.000Z',
    status: 'waiting',
  },
];
export const mockLegalDocuments: LegalDocument[] = [
  {
    id: 'legal-terms-001',
    type: 'terms',
    titleAr: 'الشروط والأحكام التجريبية',
    contentAr: 'محتوى تجريبي غير قانوني وغير نهائي.',
    version: 'mock-1',
    isActive: true,
    publishedAt: T,
  },
];
export const mockFAQItems: FAQItem[] = [
  {
    id: 'faq-001',
    questionAr: 'كيف أرسل طلباً؟',
    answerAr: 'إجابة تجريبية ستستخدم في المحاكاة.',
    displayOrder: 1,
    isActive: true,
  },
];
export const mockAdminReportSummary: AdminReportSummary = {
  totalCustomers: 3,
  activeCustomers: 2,
  totalProviders: 4,
  approvedProviders: 2,
  pendingProviders: 1,
  requestsByStatus: [
    { key: 'completed', labelAr: 'مكتملة', value: 1 },
    { key: 'cancelled', labelAr: 'ملغاة', value: 1 },
  ],
  requestsByArea: [
    { key: 'baghdad', labelAr: 'بغداد', value: 4 },
    { key: 'basra', labelAr: 'البصرة', value: 2 },
  ],
  requestsByService: serviceCodes.map((code) => ({
    key: code,
    labelAr: serviceLabels[code],
    value: mockRequests.filter((item) => item.serviceCategoryId === code).length,
  })),
  offersSubmitted: 4,
  averageOffersPerRequest: 0.67,
  acceptedOffers: 2,
  completedRequests: 1,
  cancelledRequests: 1,
  averageProviderRating: 4.2,
  bannerImpressions: 1870,
  bannerClicks: 101,
  notificationDeliveries: 1,
  notificationOpens: 0,
  growth: [{ period: '2026-01', customers: 3, providers: 4, requests: 6 }],
  generatedAt: T,
};
